<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\City;
use App\Models\Currency;
use App\Models\Product;
use App\Models\Status;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $status = Status::where('code', 'active')->first();
        $cities = City::get();
        $user = User::where('email', 'irwndandka@gmail.com')->first();
        $currency = Currency::where('code', 'SGD')->first();

        $products = [
            [
                'name' => 'Tokyo City Highlights',
                'slug' => 'tokyo-city-highlights',
                'trip_length' => 3,
                'description' => 'This tour takes you through the heart of Tokyo, a vibrant metropolis where tradition meets modernity. Begin your journey at the iconic Shibuya Crossing before heading to the historic Asakusa district to visit the famous Senso-ji Temple. Enjoy breathtaking city views from the Tokyo Skytree and savor traditional Japanese street food along Nakamise Street. Perfect for first-time visitors who want to explore the best of Tokyo in one comprehensive trip',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Tokyo')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Tokyo Culture & Cuisine',
                'slug' => 'tokyo-culture-cuisine',
                'trip_length' => 4,
                'description' => 'Dive into the cultural and culinary heart of Tokyo with this immersive experience. Learn to make sushi from a professional chef, participate in a traditional Japanese tea ceremony, and visit the Edo-Tokyo Museum to discover the city’s rich history. In the evening, explore the vibrant nightlife of Shinjuku and enjoy a multi-course kaiseki dinner. Ideal for culture lovers and foodies seeking a deeper connection with Tokyo.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Tokyo')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Busan Beach Escape',
                'slug' => 'busan-beach-escape',
                'trip_length' => 3,
                'description' => 'Unwind and soak in the coastal beauty of Busan. Spend time on the sandy shores of Haeundae Beach, explore the lively Jagalchi Fish Market, and admire the colorful houses of Gamcheon Culture Village. Relax with a traditional Korean spa experience and enjoy a delicious Korean BBQ dinner. This tour is perfect for those seeking relaxation with a splash of local culture.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Busan')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Busan Heritage Trail',
                'slug' => 'busan-heritage-trail',
                'trip_length' => 2,
                'description' => "Discover Busan's rich history and cultural heritage on this insightful tour. Visit the serene Beomeosa Temple nestled on the mountainside, stroll through the Busan Modern History Museum, and take in panoramic views from Yongdusan Park. Along the way, savor local dishes like milmyeon (cold noodles) and sweet hoddeok. A perfect journey for history buffs and cultural explorers.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Busan')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Beijing Imperial Wonders',
                'slug' => 'beijing-imperial-wonders',
                'trip_length' => 4,
                'description' => 'Step into the grandeur of ancient China with visits to some of Beijing’s most iconic landmarks. Explore the majestic Forbidden City, stand in awe at Tiananmen Square, and hike the scenic Mutianyu section of the Great Wall of China. Enjoy a traditional costume photoshoot and a classic Peking duck dinner. A must-do for travelers interested in history, culture, and timeless architecture.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Beijing')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Beijing Local Living',
                'slug' => 'beijing-local-living',
                'trip_length' => 3,
                'description' => 'Experience the authentic rhythms of local life in Beijing. Wander through traditional hutong alleys by rickshaw, join a calligraphy and paper-cutting workshop, and watch a live Chinese opera performance in a local theater. You’ll also enjoy a home-cooked dinner with a local family and sample beloved street snacks like jianbing and tanghulu. A perfect choice for travelers who want to live like a local.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Beijing')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Bali Island Escape',
                'slug' => 'bali-island-escape',
                'trip_length' => 4,
                'description' => 'Experience the magic of Bali with a perfect blend of relaxation and cultural exploration. Visit iconic temples like Tanah Lot and Uluwatu, stroll through the emerald rice terraces of Ubud, and unwind on the white-sand beaches of Seminyak. Enjoy traditional Balinese dance performances, indulge in spa treatments, and sample delicious local cuisine. Ideal for couples and solo travelers looking for a tropical escape.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Bali')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Yogyakarta Heritage Journey',
                'slug' => 'yogyakarta-heritage-journey',
                'trip_length' => 3,
                'description' => 'Dive into the cultural soul of Java in Yogyakarta, a city rich in history and tradition. Explore the majestic Borobudur and Prambanan temples, ride a becak through Malioboro Street, and watch craftsmen create batik and silverwork in Kotagede. The tour also includes a taste of local cuisine and an evening Ramayana Ballet performance with Prambanan as the backdrop. Perfect for culture and history lovers.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Yogyakarta')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Bangkok City & Temple Tour',
                'slug' => 'bangkok-city-temple-tour',
                'trip_length' => 3,
                'description' => 'Discover the vibrant energy and deep spirituality of Bangkok. Visit iconic sites like the Grand Palace, Wat Pho, and Wat Arun. Cruise along the Chao Phraya River, explore floating markets, and enjoy street food in Yaowarat (Chinatown). In the evenings, enjoy the nightlife at rooftop bars or night markets. A great tour for first-time visitors seeking to explore the dynamic culture of the Thai capital.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Bangkok')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Chiang Mai Nature & Culture',
                'slug' => 'chiang-mai-nature-culture',
                'trip_length' => 4,
                'description' => "Escape to northern Thailand’s serene landscapes and rich traditions. Visit the ancient temples of Doi Suthep, take part in a Thai cooking class, and spend a day at an ethical elephant sanctuary. The journey includes exploring local handicraft villages and enjoying cooler mountain air. Perfect for travelers seeking a mix of culture, nature, and meaningful interactions.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Chiang Mai')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Hanoi & Halong Bay Discovery',
                'slug' => 'hanoi-halong-bay-discovery',
                'trip_length' => 4,
                'description' => "Begin your journey in Vietnam’s historic capital, Hanoi, with visits to Ho Chi Minh Mausoleum, the Old Quarter, and Temple of Literature. Then embark on a luxury overnight cruise in Halong Bay, surrounded by towering limestone karsts and tranquil emerald waters. Includes kayaking, cave exploration, and seafood feasts onboard. A must for travelers who want to see the best of northern Vietnam.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Hanoi')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Ho Chi Minh & Mekong Delta Explorer',
                'slug' => 'ho-chi-minh-mekong-delta-explorer',
                'trip_length' => 3,
                'description' => 'Explore the vibrant life of southern Vietnam, starting with the bustling streets of Ho Chi Minh City. Visit historical sites like the War Remnants Museum and Cu Chi Tunnels. Then journey to the Mekong Delta for a boat tour through coconut groves and floating markets. Includes home-cooked lunch in a local village and cultural performances. Ideal for adventurers and culture seekers.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Ho Chi Minh City')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Kuala Lumpur Urban Discovery',
                'slug' => 'kuala-lumpur-urban-discovery',
                'trip_length' => 3,
                'description' => "Discover Malaysia’s capital with a mix of modern marvels and cultural heritage. Snap photos at the Petronas Towers, explore the Batu Caves, and stroll through the colonial-era buildings around Merdeka Square. Savor local flavors at Jalan Alor night market and visit museums and art galleries. Great for travelers who love urban energy with cultural depth.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Kuala Lumpur')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Langkawi Island Retreat',
                'slug' => 'langkawi-island-retreat',
                'trip_length' => 4,
                'description' => 'Unwind in the natural paradise of Langkawi. Ride the SkyCab for breathtaking views, relax on Pantai Cenang Beach, and explore mangroves by boat. Visit the Langkawi Geopark and enjoy duty-free shopping. This tour offers the perfect mix of relaxation and soft adventure for families, honeymooners, or beach lovers.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Langkawi')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Rome Ancient Wonders',
                'slug' => 'rome-ancient-wonders',
                'trip_length' => 4,
                'description' => "Step back in time and explore the heart of ancient Rome. This tour includes visits to the iconic Colosseum, the Roman Forum, and the Pantheon, where you’ll immerse yourself in the rich history of the Roman Empire. Continue your journey to the Vatican City to see St. Peter’s Basilica and the breathtaking Sistine Chapel. Perfect for history enthusiasts and those looking to discover the ancient roots of Western civilization.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Rome')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Rome City & Culinary Delights',
                'slug' => 'rome-city-culinary-delights',
                'trip_length' => 3,
                'description' => "Indulge in Rome’s culinary delights while exploring its majestic cityscape. This tour takes you through the historic city center, from the Trevi Fountain to the Spanish Steps. In the evenings, enjoy exclusive food experiences, including a traditional Roman cooking class, wine tasting, and a pizza-making workshop. A true immersion into both Rome’s history and its gastronomic heritage.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Rome')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'London Landmarks & Royal History',
                'slug' => 'london-landmarks-royal-history',
                'trip_length' => 3,
                'description' => "Discover the charm and grandeur of London, starting with the iconic Big Ben, the Houses of Parliament, and the Tower of London. Visit the famous Buckingham Palace and witness the Changing of the Guard ceremony. This tour also includes a cruise along the River Thames and a visit to the British Museum. Ideal for first-time visitors and anyone interested in Britain’s royal heritage and cultural history.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'London')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'London Theatrical & Cultural Escape',
                'slug' => 'london-theatrical-cultural-escape',
                'trip_length' => 3,
                'description' => "A perfect tour for theater lovers and culture seekers. Explore London's West End, where you can watch world-renowned musicals and plays. Visit art galleries like the Tate Modern and National Gallery, followed by a walk through Covent Garden’s artistic streets. Discover the hidden gems of London, including its vibrant markets and street food scene, all while enjoying the rich cultural fabric of the city.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'London')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Lisbon City Highlights',
                'slug' => 'lisbon-city-highlights',
                'trip_length' => 3,
                'description' => "Experience the charm of Lisbon, a city filled with colorful streets, historic landmarks, and delicious food. This tour includes a visit to the iconic Belem Tower, Jerónimos Monastery, and the charming Alfama district. Enjoy a tram ride through the hills of the city and explore the vibrant Baixa and Chiado neighborhoods. A perfect blend of Lisbon’s rich history and modern-day energy.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Lisbon')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Lisbon & Sintra Escapade',
                'slug' => 'lisbon-sintra-escapade',
                'trip_length' => 4,
                'description' => 'Explore the best of Lisbon and the enchanting town of Sintra. Begin your journey with a walking tour of Lisbon, including its famous neighborhoods and viewpoints. Then take a day trip to Sintra, a UNESCO World Heritage site, to visit the whimsical Pena Palace and the mystical Quinta da Regaleira. A combination of urban exploration and fairytale landscapes, ideal for lovers of history, nature, and architecture.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Lisbon')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Riyadh City & Heritage Exploration',
                'slug' => 'riyadh-city-heritage-exploration',
                'trip_length' => 3,
                'description' => "Discover the modern and ancient marvels of Riyadh, the capital of Saudi Arabia. Begin with a visit to the National Museum to delve into the country’s rich history. Explore the Al-Masmak Fortress, a symbol of Riyadh’s past, before heading to the Kingdom Centre Tower for panoramic city views. In the evening, experience the local souks and sample authentic Saudi cuisine. Perfect for those interested in a blend of culture, history, and modernity.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Riyadh')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Riyadh & Al-Ula Adventure',
                'slug' => 'riyadh-al-ula-adventure',
                'trip_length' => 4,
                'description' => 'Venture beyond Riyadh to Al-Ula, home to one of the most fascinating archaeological sites in the world. Tour the ancient ruins of the Nabatean city of Al-Ula, including the stunning Madain Saleh, a UNESCO World Heritage site. Return to Riyadh and explore the futuristic cityscape, including the Riyadh Sky Bridge and Riyadh Boulevard. A perfect blend of ancient history and modern-day Saudi Arabia.',
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Riyadh')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Cairo & The Pyramids of Giza',
                'slug' => 'cairo-pyramids-giza',
                'trip_length' => 3,
                'description' => "A must-see tour for anyone visiting Cairo! This journey includes a visit to the legendary Pyramids of Giza and the iconic Sphinx. Explore the Egyptian Museum, where you’ll find the treasures of King Tutankhamun and countless artifacts from ancient Egypt. Enjoy a boat ride along the Nile River at sunset, and delve into the rich culture of Egypt through its vibrant markets and restaurants. Ideal for history lovers and those seeking to understand ancient Egypt’s legacy.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Cairo')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Cairo & Alexandria Discovery',
                'slug' => 'cairo-alexandria-discovery',
                'trip_length' => 4,
                'description' => "Explore two of Egypt’s most iconic cities. Start in Cairo, visiting the Pyramids of Giza and the Egyptian Museum, before traveling to Alexandria on the Mediterranean coast. In Alexandria, visit the historic Bibliotheca Alexandrina, the Catacombs of Kom El Shoqafa, and the Citadel of Qaitbay. This tour offers a perfect mix of Cairo’s ancient wonders and Alexandria’s Mediterranean charm.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Cairo')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Kuwait City Heritage & Modern Marvels',
                'slug' => 'kuwait-city-heritage-modern-marvels',
                'trip_length' => 3,
                'description' => "Explore the contrasts of Kuwait City, where modern architecture blends with rich history. Visit the Grand Mosque, the Tareq Rajab Museum, and the Kuwait Towers, which offer stunning views of the Arabian Gulf. Stroll through the vibrant souks and shop for traditional Kuwaiti crafts. In the evenings, experience the city’s modern shopping malls and waterfront dining options. Ideal for travelers interested in both culture and modern-day attractions.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Kuwait City')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
            [
                'name' => 'Kuwait City & Desert Adventure',
                'slug' => 'kuwait-city-desert-adventure',
                'trip_length' => 4,
                'description' => "For those seeking adventure, this tour combines Kuwait City’s cultural attractions with a thrilling desert experience. Explore the city’s landmarks, including the Kuwait National Museum and the historic Kuwait Towers. Then, head to the desert for a safari in the sand dunes, followed by a traditional Bedouin-style dinner under the stars. This tour offers a unique combination of urban exploration and thrilling desert landscapes.",
                'date_from' => '2025-05-01',
                'date_until' => '2025-10-31',
                'user_id' => $user->id,
                'city_id' => $cities->where('name', 'Kuwait City')->first()->id,
                'purchase_currency_id' => $currency->id,
                'sales_currency_id' => $currency->id,
                'status_id' => $status->id,
            ],
        ];

        DB::transaction(function () use ($products) {
            foreach ($products as $product) {
                Product::create($product);
            }
        });
    }
}
